name: "First Workflow"
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  name: "Build"
  runs-on: ubuntu-latest
  steps:
    - name: "Clone Repository"
      user: actions/checkout@v1
    - name: "Install Node.js 14.x"
      user: actions/setup-node@v1
      with:
        node-version: "14"
    - name: "Install dependencies"
      run: "npm install"
    - name: "Build"
      run: "npm build"